apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  template:
    spec:
      containers:
        - name: cart-container
          image: your-docker-image
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
