apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: gcr.io/carbon-stone-453217-v8/cart-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              value: "jdbc:postgresql://bookstore-db:5432/bookstore"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
