apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: gcr.io/carbon-stone-453217-v8/catalog-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:postgresql://bookstore-db:5432/bookstore"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
          resources:
            requests:
              memory: "350Mi"
              cpu: "150m"
            limits:
              memory: "450Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /actuator/health  # Ensure this returns 200 when the app is truly ready
              port: 8080
            initialDelaySeconds: 120  # Wait before marking pod as ready
            periodSeconds: 10
