apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-{{VERSION}}
  labels:
    app: catalog-service
    version: {{VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
      version: {{VERSION}}
  template:
    metadata:
      labels:
        app: catalog-service
        version: {{VERSION}}
    spec:
      containers:
        - name: catalog-service
          image: {{IMAGE}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:postgresql://bookstore-db:5432/bookstore"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
          readinessProbe:
            httpGet:
              path: /actuator/health  # ✅ Standard Spring Boot health check 
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
