apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend
spec:
  replicas: 2  # Number of frontend instances
  selector:
    matchLabels:
      app: bookstore-frontend
  template:
    metadata:
      labels:
        app: bookstore-frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/carbon-stone-453217-v8/bookstore-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_CATALOG_API_URL
              value: "http://34.142.90.80:8080/api/catalog"
            - name: REACT_APP_CART_API_URL
              value: "http://bookstore-cart-service:8081/api/cart"
