apiVersion: v1
kind: Service
metadata:
  name: bookstore-db
spec:
  selector:
    app: bookstore-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  # Enables internal DNS resolution in Kubernetes
