apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-service
spec:
  template:
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5432
            initialDelaySeconds: 3
            periodSeconds: 5
